name: 'Deployment'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build
        # Use "|" for multi-line commands or "&&" to ensure build only runs if install succeeds
        run: |
          npm ci
          npm run build

      - name: Deploy to Cloudflare Pages
        uses: andykenward/github-actions-cloudflare-pages@v3.0.0
        id: pages
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
